---
- name: check cisco ios running version
  hosts: router
  connection: local

  tasks:
    - name: collect and validate version
      ios_command:
        commands: show version
        provider: "{{ cli_auth_provider }}"
      register: shver

    - debug: msg="{{ shver.stdout }}"
