---
- name: configure R3
  hosts: R3
  connection: local

  tasks:
    - name: configure dot1q port on R3 vlan 1
      ios_config:
        lines:
          - encapsulation dot1q 1
          - ip address 192.168.100.1 255.255.255.0
        parents: interface g0/2.1
        provider: "{{ cli_auth_provider }}"

    - name: configure dot1q port on R3 vlan 2
      ios_config:
        lines:
          - encapsulation dot1q 2
          - ip address 192.168.200.1 255.255.255.0
        parents: interface g0/2.2
        provider: "{{ cli_auth_provider }}"

---
- name: configure R2
  hosts: R2
  connection: local

    - name: configure dot1q port on R2 vlan 1
      ios_config:
        lines:
          - encapsulation dot1q 1
          - ip address 10.1.1.1 255.255.255.0
        parents: interface g0/2.1
        provider: "{{ cli_auth_provider }}"

    - name: configure dot1q port on R2 vlan 2
      ios_config:
        lines:
          - encapsulation dot1q 2
          - ip address 10.2.2.1 255.255.255.0
        parents: interface g0/2.2
        provider: "{{ cli_auth_provider }}"
---
- name: configure S1
  hosts: S1
  connection: local

    - name: configure trunk port on S1
      ios_config:
        lines:
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
        parents: interface g0/1
        provider: "{{ cli_auth_provider }}"

---
- name: configure S2
  hosts: S2
  connection: local
  
    - name: configure trunk port on S2
      ios_config:
        lines:
          - switchport trunk encap dot1q
          - switchport mode trunk
        parents: interface g0/1
        provider: "{{ cli_auth_provider }}"
