---
- name: configure OSPF on the routers
  hosts: localhost
  connection: local

  vars_prompt:
    - name: router_pass
      prompt: "Password"

  vars:
    R1:
      host: 172.16.1.106
      username: gdykeman
      password: "{{ router_pass }}"
      transport: cli
    R2:
      host: 172.16.1.107
      username: gdykeman
      password: "{{ router_pass }}"
      transport: cli
    R3:
      host: 172.16.1.75
      username: gdykeman
      password: "{{ router_pass }}"
      transport: cli

  tasks:
    - name: configure interface G0/1 on R1
      ios_config:
        lines:
          - ip address 10.0.0.1 255.255.255.0
          - no shut
        parents: interface g0/1
        provider: "{{ R1 }}"

    - name: configure loopback 0 on R1
      ios_config:
        lines:
          - interface loopback 0
          - ip address 1.1.1.1 255.255.255.0
        provider: "{{ R1 }}"

    - name: configure OSPF area 0 on R1
      ios_config:
        lines:
          - network 10.0.0.0 0.0.0.255 area 0
          - network 10.1.1.0 0.0.0.255 area 0
          - network 10.2.2.0 0.0.0.255 area 0
        parents: router ospf 1
        provider: "{{ R1 }}"

    - name: OSPF Template
      template: src=router.j2 dest=/tmp/.cfg

    - name: configure interface G0/1 on R2
      ios_config:
        lines:
          - ip address 10.0.0.2 255.255.255.0
          - no shut
        parents: interface g0/1
        provider: "{{ R2 }}"

    - name: configure loopback 0 on R2
      ios_config:
        lines:
          - interface loopback 0
          - ip address 2.2.2.2 255.255.255.0
        provider: "{{ R2 }}"

    - name: configure OSPF area 0 on R2
      ios_config:
        lines:
          - network 10.0.0.0 0.0.0.255 area 0
          - network 10.1.1.0 0.0.0.255 area 0
          - network 10.2.2.0 0.0.0.255 area 0
        parents: router ospf 1
        provider: "{{ R2 }}"
