---
- name: Configure Redistribution OSPF & EIGRP on the routers
  hosts: localhost
  connection: local

  vars_prompt:
    - name: router_pass
      prompt: "Password"

  vars:
    R1:
      host: 172.16.1.106
      username: gdykeman
      password: "{{ router_pass }}"
      transport: cli

  tasks:
    - name: Redistribute OSPF into EIGRP
      ios_config:
        lines:
          - network 192.168.1.0
          - redistribute ospf 1
          - default-metric 10000 100 255 1 2500
        parents: router eigrp 1
        provider: "{{ R1 }}"

    - name: Redistribute EIGRP into OSPF
      ios_config:
        lines:
          - network 10.0.0.0 0.0.0.255 area 0
          - redistribute eigrp 1 metric 100 subnets
        parents: router ospf 1
        provider: "{{ R1 }}"
