---
- name: configure EIGRP on the routers
  hosts: localhost
  connection: local

  vars_prompt:
    - name: router_pass
      prompt: "Password"

  vars:
    R1:
      host: 172.16.1.106
      username: gdykeman
      password: "{{ router_pass }}"
      transport: cli
    R2:
      host: 172.16.1.74
      username: gdykeman
      password: "{{ router_pass }}"
      transport: cli
    R3:
      host: 172.16.1.108
      username: gdykeman
      password: "{{ router_pass }}"
      transport: cli

  tasks:
    - name: configure interface G0/2 on R1
      ios_config:
        lines:
          - ip address 192.168.1.1 255.255.255.0
          - no shut
        parents: interface g0/2
        provider: "{{ R1 }}"

    - name: configure loopback 0 on R1
      ios_config:
        lines:
          - interface loopback 0
          - ip address 1.1.1.1 255.255.255.0
        provider: "{{ R1 }}"

    - name: configure Eigrp on R1
      ios_config:
        lines:
          - network 192.168.1.0 0.0.0.255
          - network 192.168.100.0 0.0.0.255
          - network 192.168.200.0 0.0.0.255
        parents: router eigrp 1
        provider: "{{ R1 }}"

    - name: configure interface G0/1 on R3
      ios_config:
        lines:
          - ip address 192.168.1.2 255.255.255.0
          - no shut
        parents: interface g0/1
        provider: "{{ R3 }}"

    - name: configure loopback 0 on R3
      ios_config:
        lines:
          - interface loopback 0
          - ip address 3.3.3.3 255.255.255.0
        provider: "{{ R3 }}"

    - name: configure Eigrp on R3
      ios_config:
        lines:
          - network 192.168.1.0 0.0.0.255
          - network 192.168.100.0 0.0.0.255
          - network 192.168.200.0 0.0.0.255
        parents: router eigrp 1
        provider: "{{ R3 }}"
