---
- name: configure OSPF on R1
  hosts: R1
  connection: local

  tasks:
    - name: configure interface G0/1 on R1
      ios_config:
        lines:
          - ip address 10.0.0.1 255.255.255.0
          - no shut
        parents: interface g0/1
        provider: "{{ cli_auth_provider }}"

    - name: configure loopback 0 on R1
      ios_config:
        lines:
          - interface loopback 0
          - ip address 1.1.1.1 255.255.255.0
        provider: "{{ cli_auth_provider }}"

    - name: configure OSPF area 0 on R1
      ios_config:
        lines:
          - network 10.0.0.0 0.0.0.255 area 0
          - network 10.1.1.0 0.0.0.255 area 0
          - network 10.2.2.0 0.0.0.255 area 0
        parents: router ospf 1
        provider: "{{ cli_auth_provider }}"

---
- name: configure OSPF on R2
  hosts: R2
  connection: local

    - name: configure interface G0/1 on R2
      ios_config:
        lines:
          - ip address 10.0.0.2 255.255.255.0
          - no shut
        parents: interface g0/1
        provider: "{{ cli_auth_provider }}"

    - name: configure loopback 0 on R2
      ios_config:
        lines:
          - interface loopback 0
          - ip address 2.2.2.2 255.255.255.0
        provider: "{{ cli_auth_provider }}"

    - name: configure OSPF area 0 on R2
      ios_config:
        lines:
          - network 10.0.0.0 0.0.0.255 area 0
          - network 10.1.1.0 0.0.0.255 area 0
          - network 10.2.2.0 0.0.0.255 area 0
        parents: router ospf 1
        provider: "{{ cli_auth_provider }}"
