---
- name: gather configuration files
  hosts: router
  connection: local

  vars_prompt:
    - name: router_pass
      prompt: "Password"

  vars:
    cli:
      host: "{{ ansible_host }}"
      username: gdykeman
      password: "{{ router_pass }}"
      transport: cli

  tasks:
