---
- name: Configure Redistribution on the SMB routers
  hosts: R1
  connection: local

  tasks:
    - name: Redistribute OSPF into EIGRP on R1
      ios_config:
        lines:
          - network 192.168.0.1
          - redistribute ospf 1
          - default-metric 10000 100 255 1 2500
        parents: router eigrp 1
        provider: "{{ cli_auth_provider }}"

    - name: Redistribute EIGRP into OSPF on R1
      ios_config:
        lines:
          - network 10.0.0.0 0.0.0.255 area 0
          - redistribute eigrp 1 metric 100 subnets
        parents: router ospf 1
        provider: "{{ cli_auth_provider }}"
