---
- name: configuration of router interfaces for smb
  hosts: R1
  connection: local
  tasks:
    - name: configure interface G0/1 on R1
      ios_config:
        lines:
          - ip address 10.0.0.1 255.255.255.0
          - no shut
        parents: interface g0/1
        provider: "{{ cli_auth_provider }}"

    - name: configure interface G0/2 on R1
      ios_config:
        lines:
          - ip address 192.168.0.1 255.255.255.0
          - no shut
        parents: interface g0/2
        provider: "{{ cli_auth_provider }}"

    - name: configure loopback 0 on R1
      ios_config:
        lines:
          - interface loopback 0
          - ip address 1.1.1.1 255.255.255.0
        provider: "{{ cli_auth_provider }}"

    - name: configure loopback 1 on R1
      ios_config:
        lines:
          - interface loopback 0
          - ip address 10.10.10.10 255.255.255.0
        provider: "{{ cli_auth_provider }}"

#######################################################

- name: configuration of router interfaces for smb
  hosts: R2
  connection: local
  tasks:
    - name: configure interface G0/1 on R2
      ios_config:
        lines:
          - ip address 10.0.0.2 255.255.255.0
          - no shut
        parents: interface g0/1
        provider: "{{ cli_auth_provider }}"

    - name: configure interface G0/2 on R2
      ios_config:
        lines:
          - ip address 172.16.0.2 255.255.255.0
          - no shut
        parents: interface g0/2
        provider: "{{ cli_auth_provider }}"

    - name: configure loopback 0 on R2
      ios_config:
        lines:
          - interface loopback 0
          - ip address 2.2.2.2 255.255.255.0
        provider: "{{ cli_auth_provider }}"

    - name: configure loopback 1 on R2
      ios_config:
        lines:
          - interface loopback 1
          - ip address 20.20.20.20 255.255.255.0
        provider: "{{ cli_auth_provider }}"

#######################################################

- name: configuration of router interfaces for smb
  hosts: R3
  connection: local
  tasks:
    - name: configure interface G0/1 on R3
      ios_config:
        lines:
          - ip address 172.16.0.3 255.255.255.0
          - no shut
        parents: interface g0/1
        provider: "{{ cli_auth_provider }}"

    - name: configure interface G0/2 on R3
      ios_config:
        lines:
          - ip address 192.168.0.3 255.255.255.0
          - no shut
        parents: interface g0/2
        provider: "{{ cli_auth_provider }}"

    - name: configure loopback 0 on R3
      ios_config:
        lines:
          - interface loopback 0
          - ip address 3.3.3.3 255.255.255.0
        provider: "{{ cli_auth_provider }}"

    - name: configure loopback 1 on R3
      ios_config:
        lines:
          - interface loopback 1
          - ip address 30.30.30.30 255.255.255.0
        provider: "{{ cli_auth_provider }}"
