---
- name: configure OSPF on R1
  hosts: R1
  connection: local
  tasks:
          ##### CONFIGURE OSPF R1 - R2 #####
    - name: configure OSPF area 0 on R1
      template:
        src: templates/router.j2
