---
- name: configuration of network for small business
  hosts: R1
  connection: local

  tasks:
          ##### CONFIGURE OSPF R1 - R2 #####
    - name: configure OSPF area 0 on R1
      ios_config:
        lines:
          - network 10.0.0.0 0.0.0.255 area 0
          - network 1.1.1.0 0.0.0.255 area 0
        parents: router ospf 1
        provider: "{{ cli_auth_provider }}"
          ##### CONFIGURE EIGRP R1 - R3 #####
    - name: configure Eigrp on R1
      ios_config:
        lines:
          - network 192.168.0.0 0.0.0.255
          - network 10.10.10.10 0.0.0.0
        parents: router eigrp 1
        provider: "{{ cli_auth_provider }}"

---
- name: configuration of network for small business
  hosts: R2
  connection: local
          ##### CONFIGURE OSPF R2 - R1 #####
    - name: configure OSPF area 0 on R2
      ios_config:
        lines:
          - network 10.0.0.0 0.0.0.255 area 0
          - network 2.2.2.0 0.0.0.255 area 0
        parents: router ospf 1
        provider: "{{ cli_auth_provider }}"
          ##### CONFIGURE RIP R2 - R3 #####
    - name: configure RIP on R2
      ios_config:
        lines:
          - network 172.16.0.0
          - network 20.20.20.20
        parents: router rip
        provider: "{{ cli_auth_provider }}"

---
- name: configuration of network for small business
  hosts: R3
  connection: local
          ##### CONFIGURE EIGRP R3 - R1 #####
    - name: configure Eigrp on R3
      ios_config:
        lines:
          - network 192.168.0.0 0.0.0.255
          - network 3.3.3.3 0.0.0.0
        parents: router eigrp 1
        provider: "{{ cli_auth_provider }}"


          ##### CONFIGURE RIP R3 - R2 #####
    - name: configure RIP on R3
      ios_config:
        lines:
          - network 172.16.0.0
          - network 30.30.30.30
        parents: router rip
        provider: "{{ cli_auth_provider }}"
