---
- name: Configuration S2 interfaces
  hosts: S2
  connection: local

  tasks:
    - name: configure interface on S2
      ios_config:
        lines:
          - interface vlan 1
          - ip address 10.1.0.120 255.255.255.0
          - interface vlan 2
          - ip address 10.2.0.120 255.255.255.0
          - interface vlan 3
          - ip address 172.16.0.120 255.255.255.0
          - interface vlan 4
          - ip address 172.17.0.120 255.255.255.0
        provider: "{{ cli_auth_provider }}"

    - name: configure interface on S2
      ios_config:
        lines:
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
        parents: int g0/1
        provider: "{{ cli_auth_provider }}"

    - name: configure interfaces on S2
      ios_config:
        lines:
          - no shut
        parents: int vlan 1
        provider: "{{ cli_auth_provider }}"

    - name: configure interfaces on S2
      ios_config:
        lines:
          - no shut
        parents: int vlan 2
        provider: "{{ cli_auth_provider }}"

    - name: configure interfaces on S2
      ios_config:
        lines:
          - no shut
        parents: int vlan 3
        provider: "{{ cli_auth_provider }}"

    - name: configure interfaces on S2
      ios_config:
        lines:
          - no shut
        parents: int vlan 4
        provider: "{{ cli_auth_provider }}"

    - name: configure interface on S2
      ios_config:
        lines:
          - no shut
        parents: int g0/1
        provider: "{{ cli_auth_provider }}"
---
- name: Configuration R2 interface for inter-vlan
  hosts: R2
  connection: local

    - name: configure trunk on R2
      ios_config:
        lines:
          - no shut
        parents: int g0/3
        provider: "{{ cli_auth_provider }}"

    - name: configure trunk on R2
      ios_config:
        src: templates/dot1q.j2
        provider: "{{ cli_auth_provider }}"
